server:
  port: 8081

spring:
  application:
    name: ORDER-SERVICE
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/orderdb
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update
  config:
    import: configserver:${CONFIG_SERVER_URL:http://localhost:9296}

logging:
  level:
    org:
      springframework:
        web:
          servlet:
            DispatcherServlet: DEBUG
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
management:
  tracing:
    sampling:
      probability: 1.0

feign:
  circuitbreaker:
    enabled: true

resilience4j:
  circuitbreaker:
  instances:
    external:
      registerHealthIndicator: true
      eventConsumerBufferSize: 10
      automaticTransitionFromOpenToHalfOpenEnabled: true
      failureRateThreshold: 50
      minimumNumberOfCalls: 5
      permittedNumberOfCallsInHalfOpenState: 3
      slidingWindowSize: 10
      waitDurationInOpenState: 5s
      slidingWindowType: COUNT_BASED




#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}